openapi: 3.0.1
info:
  title: IP Echo
  version: 1.0.0
  description: A simple no-logs Cloudflare Worker that returns the caller's IP address. You can read IP Echo's source code on [GitHub](https://github.com/AverageHelper/ip-echo-cloudflare).
  license:
    name: GNU General Public License v3.0
    url: https://github.com/AverageHelper/ip-echo-cloudflare/blob/main/LICENSE
servers:
  - url: https://ip.average.name
paths:
  "/":
    get:
      tags:
        - echo
      summary: Get the caller's IP address
      operationId: ip
      responses:
        200:
          description: The caller's IP address is in the body.
          content:
            text/plain:
              schema:
                type: string
                example: 127.0.0.1
            application/json:
              schema:
                type: string
                example: "127.0.0.1"
        500:
          description: The caller's IP address could not be determined, most likely due to a server configuration error.
