# On PR toward `main`: run builds, run tests, and deploy to staging

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: npm ci

      - name: Check that build succeeds
        run: npm run build

      - name: Run unit tests
        run: npm test
