# On PR toward `main`: run builds, run tests, and deploy to staging

when:
  - event: manual
  - event: pull_request
    branch: main

steps:
  build:
    name: Check that build succeeds
    image: node:18
    commands:
      - npm ci
      - npm run build

  test:
    name: Run unit tests
    image: node:18
    commands:
      - npm test
