name: Build and Test

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Lint and Build
        run: npm run build

      - name: Test
        run: npm test
