name: Validate OpenAPI Syntax

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Validate OpenAPI Syntax
        uses: mbowman100/swagger-validator-action@2.0
        with:
          files: |
            openapi.yaml
